name: speed_test
description: Uma ferramenta Dart para execução rápida e eficiente de testes unitários, especialmente otimizada para projetos Flutter.
version: 0.1.0
repository: https://github.com/aphenrique/speed_test
homepage: https://github.com/aphenrique/speed_test
documentation: https://github.com/aphenrique/speed_test/blob/main/README.md

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  speed_test: speed_test

topics:
  - test
  - flutter
  - performance
  - cli
